openapi: 3.0.0
info:
  title: Test-SV-API2
  version: 1.0.0
servers:
  - url: https://petstore.swagger.io
paths:
  /v2/pet:
    post:
      tags:
        - default
      summary: https://petstore.swagger.io/v2/pet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 0
                category:
                  id: 0
                  name: string
                name: doggie
                photoUrls:
                  - string
                tags:
                  - id: 0
                    name: string
                status: available
      parameters:
        - name: accept
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
