openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
servers:
  - url: http://api.example.com
paths:
  /hello:
    get:
      summary: Get a simple greeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Hello, World!