openapi: 3.0.0
info:
  title: WSO2 for IB (EI)
  version: 1.0.0
servers:
  - url: http://wso2uat.phillipbank.com.kh:8282
  - url: http://{{url}}
paths:
  /services/internet-banking-fcuat/casa-detail/019004994:
    get:
      tags:
        - default
      summary: Saving account info
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/loan-detail/0000031398420707:
    get:
      tags:
        - default
      summary: Loan account info
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/term-deposit-detail/000002279:
    get:
      tags:
        - default
      summary: TD account info
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-term-deposit-product:
    post:
      tags:
        - default
      summary: TD products by account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '000002279'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/loan-schedule/0000031398420707:
    get:
      tags:
        - default
      summary: Loan schedule
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-account-statements:
    post:
      tags:
        - default
      summary: Account statement
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '000000035'
                  from_date: '2020-01-01'
                  to_date: '2025-01-01'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-denomination/SMART:
    get:
      tags:
        - default
      summary: Denominations by operator
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-operators:
    get:
      tags:
        - default
      summary: Operators
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /esb/mb/v1/txn-detail:
    post:
      tags:
        - default
      summary: Transaction info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                account_no: '019005020'
                entry_no: '251909282'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/corp-accounts:
    post:
      tags:
        - default
      summary: Corporate accounts
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  cif_no: '003115782'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/corp-account-statement:
    post:
      tags:
        - default
      summary: Corporate account statement
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '011005808'
                  from_date: '2000-01-01'
                  to_date: '2030-01-01'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/corp-casa-detail:
    post:
      tags:
        - default
      summary: Corporate saving account info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '011005808'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/inquiry-corp-loan-detail:
    post:
      tags:
        - default
      summary: Corporate loan account info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '0150032402280002'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/corp-customer-detail/002830363:
    get:
      tags:
        - default
      summary: Corporate customer info
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/corp-customer-verify/00030083:
    get:
      tags:
        - default
      summary: Corporate customers by NID
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-card-detail:
    post:
      tags:
        - default
      summary: Virtual master card statement
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  card_id: '952824000000023'
                  start_date: '2020-01-01'
                  end_date: '2030-01-01'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-customer:
    post:
      tags:
        - default
      summary: Customers by NID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  id_no: '010687306'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-tenor-rate:
    post:
      tags:
        - default
      summary: Tenor rates
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  class_id: '359'
                  ccy_code: USD
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-branch:
    post:
      tags:
        - default
      summary: Branches
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-branch-code:
    post:
      tags:
        - default
      summary: Branch info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  code: '016'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-label-mapping:
    post:
      tags:
        - default
      summary: Label mapping info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  app_code: IB
                  field_code: value_dt
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-language-active:
    post:
      tags:
        - default
      summary: Languages
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  app_code: IB
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-sys-response-code:
    post:
      tags:
        - default
      summary: Response codes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  app_code: IB
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-sys-config-by-key:
    post:
      tags:
        - default
      summary: Configuration info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  app_code: IB
                  key: CAM_PHONE_PREFIX
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-sys-config-by-type:
    post:
      tags:
        - default
      summary: Configurations by type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  app_code: IB
                  type: SERVER
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/exchange-rate:
    get:
      tags:
        - default
      summary: Exchange rates
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/exchange-rate-v2:
    get:
      tags:
        - default
      summary: Exchange rates v2
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/ncf-fee:
    get:
      tags:
        - default
      summary: NCF fee
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/global-service/inquiry-partner-account:
    post:
      tags:
        - default
      summary: ESB partner account info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  branch_code: '701'
                  partner_name: WEG
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-check-book-by-account:
    post:
      tags:
        - default
      summary: Cheques by account and cheque numbers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  start_que_no: '287001'
                  stop_que_no: '287010'
                  account_no: '012001476'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-cheque-book:
    post:
      tags:
        - default
      summary: Cheque books by account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '016000537'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-cheque-book-info:
    post:
      tags:
        - default
      summary: Cheques by account and cheque book number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '016000537'
                  cheque_book_no: '008601'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /services/internet-banking/query-cheque-info:
    post:
      tags:
        - default
      summary: Cheque info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                any:
                  account_no: '016000537'
                  cheque_no: '008605'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /esb/ib/v1/branch-by-acc:
    post:
      tags:
        - default
      summary: Branch info by account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                cust_ac_no: '016000611'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
